# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: >
  The Department of Electrical and Energy Engineering of
  Institute of Technology of Cambodia(ITC)
email: oemdaro@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Department of Electrical and Energy Engineering of
  Institute of Technology of Cambodia(ITC) in collaboration with AUN/SEED-NET
  and JICA proudly present the 2016 Regional Conference on Energy Engineering
  (RCEnE 2016).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gee-itc.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

github: [metadata]

# Build settings
markdown: kramdown

# Gems plug-in
gems:
  - jekyll-redirect-from
